### PR TITLE
Removed http request and just embedded the gif

### PR DESCRIPTION
**Pull request by ChrisPritchard**
Seems a little more efficient

### CODE REVIEW

**Comment by NHAS** [comment]
This is critical to our business usecase, please merge this

**Comment by avatsaev** [comment]
This was done for a reason, I got contacted by a copyright lawyer, so to avoid potential problems, i've removed the file from the repo. Just make a fork and use it as you wish.

Also, "business use case"? what?

**Comment by ChrisPritchard** [comment]
Oh okay haha. We guessed it might be something like that. Who owns the copyright for nyancat??

**Comment by avatsaev** [comment]
prguitarman

**Comment by lachlan2k** [comment]
This PR doesn't even compile:
Screen Shot 2022-01-26 at 11 08 07 AM

**Comment by ChrisPritchard** [comment]
Maybe you just cant run xcode lachlan. Stay in your lane.

**Pull request closed without merging**
