### PR TITLE
Add an open source licence

### PR DESCRIPTION
**Pull request by chrisns**
Adding a licence means people can make changes to your code
See http://choosealicense.com/ for better documentation
Boldly suggesting a MIT licence without knowing about any of the copyrighted material on this repo that might conflict

### CODE REVIEW

**Comment by avatsaev** [comment]
Need Torress' permission on this, contacted him on email, waiting for response


On 7 Nov 2016, 4:13 PM +0100, Chris Nesbitt-Smith <notifications@github.com>, wrote:

Adding a licence means people can make changes to your code
See http://choosealicense.com/ for better documentation
Boldly suggesting a MIT licence without knowing about any of the copyrighted material on this repo that might conflict

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/avatsaev/touchbar_nyancat/pull/4

Commit Summary

  *   Add an open source licence

File Changes

  *   A LICENCE<https://github.com/avatsaev/touchbar_nyancat/pull/4/files#diff-0> (21)

Patch Links:

  *   https://github.com/avatsaev/touchbar_nyancat/pull/4.patch
  *   https://github.com/avatsaev/touchbar_nyancat/pull/4.diff

**Comment by avatsaev** [comment]
Torress said no, because Open Source licence allows selling.

**Comment by chrisns** [comment]
@avatsaev could you make it pull the nyan artwork from somewhere at runtime to allow you to open source?

**Comment by avatsaev** [comment]
I really don't wanna deal with this, let's just leave it as it is, without making the guy angry.

**Comment by chrisns** [comment]
😢 thanks for trying anyway

**Pull request merged**
